name: Deploy pythonanywhere webapp
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Upload files
      # ...

      - name: Reload webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          api-token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain-name: ${{ secrets.PYTHONANYWHERE_DOMAIN_NAME }}




      # - name: Log in to Heroku
      #   uses: akshnz/heroku-login-action@v1
      #   with:
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      # - name: Push code to Heroku
      #   run: git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git && git push heroku main
